In [32]:

# Initial imports
import pandas as pd
import numpy as np
import hvplot.pandas
from path import Path
import plotly.express as px
from sklearn.cluster import KMeans
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.cluster import AgglomerativeClustering
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from path import Path
from sklearn.preprocessing import StandardScaler



ImportError: cannot import name 'NumericInput' from 'bokeh.models.widgets' (C:\Users\12109\anaconda3\lib\site-packages\bokeh\models\widgets\__init__.py)

In [9]:
# Load the crypto_data.csv dataset.
# Load data
file_path =r"C:\Users\12109\Documents\Data boot camp\Class Work\Module 18\crypto_data.csv"
crypto_df = pd.read_csv(file_path, index_col=0)
print(crypto_df.shape)
crypto_df.head(10)

(1252, 6)


CoinName Algorithm  IsTrading ProofType  TotalCoinsMined  \
42      42 Coin    Scrypt       True   PoW/PoS     4.199995e+01   
365     365Coin       X11       True   PoW/PoS              NaN   
404     404Coin    Scrypt       True   PoW/PoS     1.055185e+09   
611   SixEleven   SHA-256       True       PoW              NaN   
808         808   SHA-256       True   PoW/PoS     0.000000e+00   
1337  EliteCoin       X13       True   PoW/PoS     2.927942e+10   
2015  2015 coin       X11       True   PoW/PoS              NaN   
BTC     Bitcoin   SHA-256       True       PoW     1.792718e+07   
ETH    Ethereum    Ethash       True       PoW     1.076842e+08   
LTC    Litecoin    Scrypt       True       PoW     6.303924e+07   

     TotalCoinSupply  
42                42  
365       2300000000  
404        532000000  
611           611000  
808                0  
1337    314159265359  
2015               0  
BTC         21000000  
ETH                0  
LTC         84000000

In [10]:
# Keep all the cryptocurrencies that are being traded.
crypto2_df = crypto_df[(crypto_df["IsTrading"] == True)]
print(crypto2_df.shape)
crypto2_df.head(10)

(1144, 6)


CoinName Algorithm  IsTrading ProofType  TotalCoinsMined  \
42      42 Coin    Scrypt       True   PoW/PoS     4.199995e+01   
365     365Coin       X11       True   PoW/PoS              NaN   
404     404Coin    Scrypt       True   PoW/PoS     1.055185e+09   
611   SixEleven   SHA-256       True       PoW              NaN   
808         808   SHA-256       True   PoW/PoS     0.000000e+00   
1337  EliteCoin       X13       True   PoW/PoS     2.927942e+10   
2015  2015 coin       X11       True   PoW/PoS              NaN   
BTC     Bitcoin   SHA-256       True       PoW     1.792718e+07   
ETH    Ethereum    Ethash       True       PoW     1.076842e+08   
LTC    Litecoin    Scrypt       True       PoW     6.303924e+07   

     TotalCoinSupply  
42                42  
365       2300000000  
404        532000000  
611           611000  
808                0  
1337    314159265359  
2015               0  
BTC         21000000  
ETH                0  
LTC         84000000

In [11]:
# Keep all the cryptocurrencies that have a working algorithm.
crypto3_df = crypto2_df.dropna(subset=["Algorithm"])
print(crypto3_df.shape)
crypto3_df.head(10)

(1144, 6)


CoinName Algorithm  IsTrading ProofType  TotalCoinsMined  \
42      42 Coin    Scrypt       True   PoW/PoS     4.199995e+01   
365     365Coin       X11       True   PoW/PoS              NaN   
404     404Coin    Scrypt       True   PoW/PoS     1.055185e+09   
611   SixEleven   SHA-256       True       PoW              NaN   
808         808   SHA-256       True   PoW/PoS     0.000000e+00   
1337  EliteCoin       X13       True   PoW/PoS     2.927942e+10   
2015  2015 coin       X11       True   PoW/PoS              NaN   
BTC     Bitcoin   SHA-256       True       PoW     1.792718e+07   
ETH    Ethereum    Ethash       True       PoW     1.076842e+08   
LTC    Litecoin    Scrypt       True       PoW     6.303924e+07   

     TotalCoinSupply  
42                42  
365       2300000000  
404        532000000  
611           611000  
808                0  
1337    314159265359  
2015               0  
BTC         21000000  
ETH                0  
LTC         84000000

In [12]:
crypto4_df = crypto3_df.drop(columns=["IsTrading"])
print(crypto4_df.shape)
crypto4_df.head()

(1144, 5)


CoinName Algorithm ProofType  TotalCoinsMined TotalCoinSupply
42     42 Coin    Scrypt   PoW/PoS     4.199995e+01              42
365    365Coin       X11   PoW/PoS              NaN      2300000000
404    404Coin    Scrypt   PoW/PoS     1.055185e+09       532000000
611  SixEleven   SHA-256       PoW              NaN          611000
808        808   SHA-256   PoW/PoS     0.000000e+00               0

In [13]:
crypto5_df = crypto4_df.dropna()
print(crypto5_df.shape)
crypto5_df.head(10)

(685, 5)


CoinName       Algorithm ProofType  TotalCoinsMined  \
42             42 Coin          Scrypt   PoW/PoS     4.199995e+01   
404            404Coin          Scrypt   PoW/PoS     1.055185e+09   
808                808         SHA-256   PoW/PoS     0.000000e+00   
1337         EliteCoin             X13   PoW/PoS     2.927942e+10   
BTC            Bitcoin         SHA-256       PoW     1.792718e+07   
ETH           Ethereum          Ethash       PoW     1.076842e+08   
LTC           Litecoin          Scrypt       PoW     6.303924e+07   
DASH              Dash             X11   PoW/PoS     9.031294e+06   
XMR             Monero  CryptoNight-V7       PoW     1.720114e+07   
ETC   Ethereum Classic          Ethash       PoW     1.133597e+08   

     TotalCoinSupply  
42                42  
404        532000000  
808                0  
1337    314159265359  
BTC         21000000  
ETH                0  
LTC         84000000  
DASH        22000000  
XMR                0  
ETC        210000000

In [14]:
# Keep the rows where coins are mined.
# crypto6_df = crypto5_df.loc[crypto5_df.TotalCoinsMined !=0]
crypto6_df = crypto5_df.drop(crypto5_df[crypto5_df.TotalCoinsMined <= 0].index)
print(crypto6_df.shape)
crypto6_df.head(8)

(532, 5)


CoinName       Algorithm ProofType  TotalCoinsMined TotalCoinSupply
42      42 Coin          Scrypt   PoW/PoS     4.199995e+01              42
404     404Coin          Scrypt   PoW/PoS     1.055185e+09       532000000
1337  EliteCoin             X13   PoW/PoS     2.927942e+10    314159265359
BTC     Bitcoin         SHA-256       PoW     1.792718e+07        21000000
ETH    Ethereum          Ethash       PoW     1.076842e+08               0
LTC    Litecoin          Scrypt       PoW     6.303924e+07        84000000
DASH       Dash             X11   PoW/PoS     9.031294e+06        22000000
XMR      Monero  CryptoNight-V7       PoW     1.720114e+07               0

In [15]:
# Create a new DataFrame that holds only the cryptocurrencies names.
CoinName_df = crypto6_df.drop(columns= ["Algorithm", "ProofType", "TotalCoinsMined", "TotalCoinSupply"])
print(CoinName_df.shape)
CoinName_df.head()

(532, 1)


CoinName
42      42 Coin
404     404Coin
1337  EliteCoin
BTC     Bitcoin
ETH    Ethereum

In [16]:
# Drop the 'CoinName' column since it's not going to be used on the clustering algorithm.
crypto_df = crypto6_df.drop(columns =["CoinName"])
print(crypto_df.shape)
crypto_df.head(10)

(532, 4)


Algorithm ProofType  TotalCoinsMined TotalCoinSupply
42            Scrypt   PoW/PoS     4.199995e+01              42
404           Scrypt   PoW/PoS     1.055185e+09       532000000
1337             X13   PoW/PoS     2.927942e+10    314159265359
BTC          SHA-256       PoW     1.792718e+07        21000000
ETH           Ethash       PoW     1.076842e+08               0
LTC           Scrypt       PoW     6.303924e+07        84000000
DASH             X11   PoW/PoS     9.031294e+06        22000000
XMR   CryptoNight-V7       PoW     1.720114e+07               0
ETC           Ethash       PoW     1.133597e+08       210000000
ZEC         Equihash       PoW     7.383056e+06        21000000

In [17]:
# Use get_dummies() to create variables for text features.
crypto8_df = pd.get_dummies(crypto_df, columns = ["Algorithm", "ProofType"])
print(crypto8_df.shape)
crypto8_df.head(5)

(532, 98)


TotalCoinsMined TotalCoinSupply  Algorithm_1GB AES Pattern Search  \
42       4.199995e+01              42                                 0   
404      1.055185e+09       532000000                                 0   
1337     2.927942e+10    314159265359                                 0   
BTC      1.792718e+07        21000000                                 0   
ETH      1.076842e+08               0                                 0   

      Algorithm_536  Algorithm_Argon2d  Algorithm_BLAKE256  Algorithm_Blake  \
42                0                  0                   0                0   
404               0                  0                   0                0   
1337              0                  0                   0                0   
BTC               0                  0                   0                0   
ETH               0                  0                   0                0   

      Algorithm_Blake2S  Algorithm_Blake2b  Algorithm_C11  ...  \
42                    0                  0              0  ...   
404                   0                  0              0  ...   
1337                  0                  0              0  ...   
BTC                   0                  0              0  ...   
ETH                   0                  0              0  ...   

      ProofType_PoW/PoS  ProofType_PoW/PoS   ProofType_PoW/PoW  \
42                    1                   0                  0   
404                   1                   0                  0   
1337                  1                   0                  0   
BTC                   0                   0                  0   
ETH                   0                   0                  0   

      ProofType_PoW/nPoS  ProofType_Pos  ProofType_Proof of Authority  \
42                     0              0                             0   
404                    0              0                             0   
1337                   0              0                             0   
BTC                    0              0                             0   
ETH                    0              0                             0   

      ProofType_Proof of Trust  ProofType_TPoS  \
42                           0               0   
404                          0               0   
1337                         0               0   
BTC                          0               0   
ETH                          0               0   

      ProofType_Zero-Knowledge Proof  ProofType_dPoW/PoW  
42                                 0                   0  
404                                0                   0  
1337                               0                   0  
BTC                                0                   0  
ETH                                0                   0  

[5 rows x 98 columns]

In [18]:
# Standardize the data with StandardScaler().
crypto_scaled = StandardScaler().fit_transform(crypto8_df)
crypto_scaled[0:5]

array([[-0.11710817, -0.1528703 , -0.0433963 , -0.0433963 , -0.0433963 ,
        -0.06142951, -0.07530656, -0.0433963 , -0.06142951, -0.06142951,
        -0.0433963 , -0.0433963 , -0.19245009, -0.06142951, -0.09740465,
        -0.0433963 , -0.11547005, -0.07530656, -0.0433963 , -0.0433963 ,
        -0.15191091, -0.0433963 , -0.13118084, -0.0433963 , -0.0433963 ,
        -0.08703883, -0.0433963 , -0.0433963 , -0.0433963 , -0.0433963 ,
        -0.06142951, -0.0433963 , -0.08703883, -0.08703883, -0.08703883,
        -0.0433963 , -0.13118084, -0.13840913, -0.13840913, -0.0433963 ,
        -0.06142951, -0.0433963 , -0.07530656, -0.18168574, -0.0433963 ,
        -0.0433963 , -0.0433963 , -0.07530656, -0.15826614, -0.31491833,
        -0.0433963 , -0.08703883, -0.07530656, -0.06142951,  1.38675049,
        -0.0433963 , -0.0433963 , -0.06142951, -0.0433963 , -0.0433963 ,
        -0.0433963 , -0.0433963 , -0.0433963 , -0.0433963 , -0.0433963 ,
        -0.0433963 , -0.39879994, -0.0433963 , -0.1

In [19]:
# Using PCA to reduce dimension to three principal components.
pca = PCA(n_components=3)
crypto_pca = pca.fit_transform(crypto_scaled)
crypto_pca

array([[-0.32969137,  1.09105341, -0.40645111],
       [-0.31304468,  1.09122814, -0.4067796 ],
       [ 2.30613632,  1.74406968, -0.37390337],
       ...,
       [ 0.33629614, -2.32209421,  0.32585712],
       [-0.20883785, -2.01682356,  0.18509313],
       [-0.29401125,  0.81707415, -0.22188833]])

In [20]:
crypto_pca_df = pd.DataFrame(data=crypto_pca, columns=["PC_1", "PC_2", "PC_3"], index = crypto_df.index)
print (crypto_pca_df.shape)
crypto_pca_df.head(10)

(532, 3)


PC_1      PC_2      PC_3
42   -0.329691  1.091053 -0.406451
404  -0.313045  1.091228 -0.406780
1337  2.306136  1.744070 -0.373903
BTC  -0.137284 -1.308498  0.148042
ETH  -0.146157 -2.062766  0.240213
LTC  -0.162336 -1.109080 -0.065102
DASH -0.383051  1.276662 -0.221550
XMR  -0.134893 -2.242933  0.285265
ETC  -0.144600 -2.062866  0.240208
ZEC  -0.208837 -2.016824  0.185093

In [21]:
inertia=[]
k = list(range(1, 11))
for i in k:
    km = KMeans(n_clusters=i, random_state=0)
    km.fit(crypto_pca_df)
    inertia.append(km.inertia_)
elbow_data = {"k": k, "inertia": inertia}
df_elbow = pd.DataFrame(elbow_data)
df_elbow.hvplot.line(x="k", y="inertia", xticks=k, title="Elbow Curve")

AttributeError: 'DataFrame' object has no attribute 'hvplot'

In [23]:
model = KMeans(n_clusters=4, random_state=0)

# Fit the model
model.fit(crypto_pca_df)

# Predict clusters
predictions = model.predict(crypto_pca_df)
print(predictions.shape)
predictions

(532,)


array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,

In [24]:
clustered_df = pd.concat([crypto_df, crypto_pca_df], axis=1)

clustered_df = pd.concat([clustered_df, CoinName_df], axis=1)

clustered_df["class"] = model.labels_

print(clustered_df.shape)
clustered_df.head(8)

(532, 9)


Algorithm ProofType  TotalCoinsMined TotalCoinSupply      PC_1  \
42            Scrypt   PoW/PoS     4.199995e+01              42 -0.329691   
404           Scrypt   PoW/PoS     1.055185e+09       532000000 -0.313045   
1337             X13   PoW/PoS     2.927942e+10    314159265359  2.306136   
BTC          SHA-256       PoW     1.792718e+07        21000000 -0.137284   
ETH           Ethash       PoW     1.076842e+08               0 -0.146157   
LTC           Scrypt       PoW     6.303924e+07        84000000 -0.162336   
DASH             X11   PoW/PoS     9.031294e+06        22000000 -0.383051   
XMR   CryptoNight-V7       PoW     1.720114e+07               0 -0.134893   

          PC_2      PC_3   CoinName  class  
42    1.091053 -0.406451    42 Coin      0  
404   1.091228 -0.406780    404Coin      0  
1337  1.744070 -0.373903  EliteCoin      0  
BTC  -1.308498  0.148042    Bitcoin      1  
ETH  -2.062766  0.240213   Ethereum      1  
LTC  -1.109080 -0.065102   Litecoin      1  
DASH  1.276662 -0.221550       Dash      0  
XMR  -2.242933  0.285265     Monero      1

In [25]:
fig = px.scatter_3d(
    clustered_df, 
    x="PC_1", 
    y="PC_2", 
    z="PC_3", 
    color="class", 
    hover_name="CoinName", 
    hover_data=["Algorithm"], 
    symbol="class", 
    width=800
)
fig.update_layout(legend=dict(x=0,y=1))
fig.show()

NameError: name 'px' is not defined

In [26]:
print('Table of Tradable Cryptocurrencies:')
print(clustered_df.shape)
clustered_df.hvplot.table(columns=['CoinName', 
                                   'Algorithm', 
                                   'ProofType', 
                                   'TotalCoinSupply',                                   
                                   'TotalCoinsMined', 
                                   'class'], 
                          width=900, 
                          sortable=True, 
                          selectable=True
                         )

Table of Tradable Cryptocurrencies:
(532, 9)


AttributeError: 'DataFrame' object has no attribute 'hvplot'

In [27]:
print(f'There are {len(clustered_df)} Total Number of Tradable Cryptocurrencies.')


There are 532 Total Number of Tradable Cryptocurrencies.


In [28]:
clustered_scaled = MinMaxScaler().fit_transform(clustered_df[['TotalCoinSupply', 'TotalCoinsMined']])
clustered_scaled

array([[4.20000000e-11, 0.00000000e+00],
       [5.32000000e-04, 1.06585544e-03],
       [3.14159265e-01, 2.95755135e-02],
       ...,
       [1.40022261e-03, 9.90135079e-04],
       [2.10000000e-05, 7.37028150e-06],
       [1.00000000e-06, 1.29582282e-07]])

In [30]:
# Create a new DataFrame that has the scaled data with the clustered_df DataFrame index.
clustered_scaled_df = pd.DataFrame(data = clustered_scaled, 
                    columns = ['TotalCoinSupply', 'TotalCoinsMined'], 
                    index = clustered_df.index)

# Add the "CoinName" column from the clustered_df DataFrame to the new DataFrame.
clustered_scaled_df['CoinName'] = clustered_df['CoinName']

# Add the "Class" column from the clustered_df DataFrame to the new DataFrame. 
clustered_scaled_df['class'] = clustered_df['class']

print(clustered_scaled_df.shape)
clustered_scaled_df.head(9)

(532, 4)


TotalCoinSupply  TotalCoinsMined          CoinName  class
42       4.200000e-11         0.000000           42 Coin      0
404      5.320000e-04         0.001066           404Coin      0
1337     3.141593e-01         0.029576         EliteCoin      0
BTC      2.100000e-05         0.000018           Bitcoin      1
ETH      0.000000e+00         0.000109          Ethereum      1
LTC      8.400000e-05         0.000064          Litecoin      1
DASH     2.200000e-05         0.000009              Dash      0
XMR      0.000000e+00         0.000017            Monero      1
ETC      2.100000e-04         0.000115  Ethereum Classic      1

In [31]:

# Create a hvplot.scatter plot using x="TotalCoinsMined" and y="TotalCoinSupply".
clustered_df.hvplot.scatter(
    x="TotalCoinsMined", 
    y="TotalCoinSupply",
    hover_cols=["CoinName"], 
    by="class"
)

AttributeError: 'DataFrame' object has no attribute 'hvplot'